// <auto-generated />
using Dotnet6EFCore.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dotnet6EFCore.Migrations
{
    [DbContext(typeof(EFCore6DBContext))]
    partial class EFCore6DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Dotnet6EFCore.Model.Heart", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("BolldPressure")
                        .HasColumnType("int");

                    b.Property<int>("Heartbeat")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Hearts");
                });

            modelBuilder.Entity("Dotnet6EFCore.Model.Human", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Humans");
                });

            modelBuilder.Entity("Dotnet6EFCore.Model.Heart", b =>
                {
                    b.HasOne("Dotnet6EFCore.Model.Human", "Human")
                        .WithOne("Heart")
                        .HasForeignKey("Dotnet6EFCore.Model.Heart", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Human");
                });

            modelBuilder.Entity("Dotnet6EFCore.Model.Human", b =>
                {
                    b.Navigation("Heart")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
